[package]
name = "emacs2nix"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.128"
tree-sitter = "=0.22.6"
tree-sitter-elisp = "1.5.0"

[build-dependencies]
cc = "1.1.16"
